services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      APP_NAME: barong-ops-console-backend
      APP_ENV: development
      APP_VERSION: 0.1.0
    ports:
      - "127.0.0.1:8000:8000"
