"""C19 durable control runtime and external chat-record boundary.

Identity, social, conversation, group, and setting metadata are durable in the
control database.  Chat records use an independently deployable store; assets
remain deliberately unconfigured and fail closed.
"""

from .storage import (
    C19_STORAGE_CAPABILITIES,
    CHAT_ASSET_STORAGE_UNCONFIGURED,
    CHAT_ASSET_STORE_OPERATIONS,
    CHAT_RECORD_STORAGE_UNCONFIGURED,
    CHAT_RECORD_STORE_OPERATIONS,
    UNCONFIGURED_CHAT_ASSET_STORE,
    UNCONFIGURED_CHAT_RECORD_STORE,
    C19StorageCapabilities,
    C19StorageUnconfiguredError,
    ChatAssetDeleteCommandDTO,
    ChatAssetDownloadIntentDTO,
    ChatAssetDTO,
    ChatAssetQuarantineCommandDTO,
    ChatAssetReferenceDTO,
    ChatAssetStore,
    ChatAssetUploadHandleDTO,
    ChatAssetUploadMetadataDTO,
    ChatPositionAdvanceDTO,
    ChatPositionQueryDTO,
    ChatReceiptPositionDTO,
    ChatRecordAppendDTO,
    ChatRecordDeleteCommandDTO,
    ChatRecordDTO,
    ChatRecordMutationResultDTO,
    ChatRecordPageDTO,
    ChatRecordQueryDTO,
    ChatRecordStore,
    ChatResumePositionDTO,
    ChatRetentionCommandDTO,
    ChatUnreadPositionDTO,
    ChatUserEventDTO,
    ChatUserEventPageDTO,
    ChatUserEventQueryDTO,
    ChatUserEventTailDTO,
    StorageCapabilityDescription,
    StorageUnconfiguredError,
    UnconfiguredChatAssetStore,
    UnconfiguredChatRecordStore,
    get_c19_storage_capabilities,
)

__all__ = [
    "C19_STORAGE_CAPABILITIES",
    "CHAT_ASSET_STORAGE_UNCONFIGURED",
    "CHAT_ASSET_STORE_OPERATIONS",
    "CHAT_RECORD_STORAGE_UNCONFIGURED",
    "CHAT_RECORD_STORE_OPERATIONS",
    "UNCONFIGURED_CHAT_ASSET_STORE",
    "UNCONFIGURED_CHAT_RECORD_STORE",
    "C19StorageCapabilities",
    "C19StorageUnconfiguredError",
    "ChatAssetDTO",
    "ChatAssetDeleteCommandDTO",
    "ChatAssetDownloadIntentDTO",
    "ChatAssetQuarantineCommandDTO",
    "ChatAssetReferenceDTO",
    "ChatAssetStore",
    "ChatAssetUploadHandleDTO",
    "ChatAssetUploadMetadataDTO",
    "ChatPositionAdvanceDTO",
    "ChatPositionQueryDTO",
    "ChatReceiptPositionDTO",
    "ChatRecordAppendDTO",
    "ChatRecordDTO",
    "ChatRecordDeleteCommandDTO",
    "ChatRecordMutationResultDTO",
    "ChatRecordPageDTO",
    "ChatRecordQueryDTO",
    "ChatRecordStore",
    "ChatResumePositionDTO",
    "ChatRetentionCommandDTO",
    "ChatUnreadPositionDTO",
    "ChatUserEventDTO",
    "ChatUserEventPageDTO",
    "ChatUserEventQueryDTO",
    "ChatUserEventTailDTO",
    "StorageCapabilityDescription",
    "StorageUnconfiguredError",
    "UnconfiguredChatAssetStore",
    "UnconfiguredChatRecordStore",
    "get_c19_storage_capabilities",
]
