from typing import Any


# C14E is a dependency binding rules layer only. These declarations do not
# register a service, grant runtime access, or create provider credentials.
MODULE_SERVICE_BINDINGS_V1: tuple[dict[str, Any], ...] = (
    {
        "module_key": "k.product_knowledge",
        "service_id": "serp",
        "binding_status": "restricted",
        "allowed_capabilities": ["serp"],
        "reason": "K product knowledge may use SERP capability after explicit key binding.",
    },
    {
        "module_key": "k.product_knowledge",
        "service_id": "deepseek",
        "binding_status": "restricted",
        "allowed_capabilities": ["reasoning", "writing"],
        "reason": "K product knowledge may use DeepSeek enrichment after explicit key binding.",
    },
    {
        "module_key": "k.product_knowledge",
        "service_id": "chatgpt",
        "binding_status": "restricted",
        "allowed_capabilities": ["reasoning", "writing"],
        "reason": "K product knowledge must use ChatGPT as the first AI keyword filter after explicit key binding.",
    },
    {
        "module_key": "k.product_knowledge",
        "service_id": "claude_opus",
        "binding_status": "restricted",
        "allowed_capabilities": ["reasoning", "writing"],
        "reason": "K product knowledge must use Claude Opus as the second AI keyword filter after explicit key binding.",
    },
    {
        "module_key": "k.product_knowledge",
        "service_id": "ai_provider",
        "binding_status": "restricted",
        "allowed_capabilities": ["reasoning", "writing"],
        "reason": "K product knowledge may use AI reasoning after explicit key binding.",
    },
    {
        "module_key": "k.product_knowledge",
        "service_id": "n8n",
        "binding_status": "restricted",
        "allowed_capabilities": ["writing"],
        "reason": "K product knowledge may hand off normalized output to downstream product workflows.",
    },
    {
        "module_key": "integration.n8n_test_bridge",
        "service_id": "n8n",
        "binding_status": "disabled",
        "allowed_capabilities": [],
        "reason": "n8n is explicitly declared but no C14E capability is enabled.",
    },
    {
        "module_key": "p.upload",
        "service_id": "n8n",
        "binding_status": "restricted",
        "allowed_capabilities": ["writing"],
        "reason": "P upload dispatches gate-checked upload packages to the n8n upload workflow.",
    },
    {
        "module_key": "p.upload",
        "service_id": "woocommerce",
        "binding_status": "restricted",
        "allowed_capabilities": ["commerce_publish"],
        "reason": "WooCommerce create/update runs only inside the n8n workflow via SKU upsert.",
    },
    {
        "module_key": "r.warehouse",
        "service_id": "keepa",
        "binding_status": "restricted",
        "allowed_capabilities": ["data_acquisition"],
        "reason": "R warehouse ingests Amazon product data through the Keepa API after key binding.",
    },
    {
        "module_key": "r.warehouse",
        "service_id": "deepseek",
        "binding_status": "restricted",
        "allowed_capabilities": ["reasoning"],
        "reason": "R warehouse uses DeepSeek category-authoritative screening after key binding.",
    },
    {
        "module_key": "r.analysis",
        "service_id": "alibaba1688",
        "binding_status": "restricted",
        "allowed_capabilities": ["data_acquisition"],
        "reason": "R analysis sources supplier candidates from 1688 keyword and image search.",
    },
    {
        "module_key": "r.analysis",
        "service_id": "rainforest",
        "binding_status": "restricted",
        "allowed_capabilities": ["data_acquisition"],
        "reason": "R analysis pulls Amazon competition signals through the Rainforest API.",
    },
    {
        "module_key": "r.analysis",
        "service_id": "serper",
        "binding_status": "restricted",
        "allowed_capabilities": ["data_acquisition"],
        "reason": "R analysis pulls channel SERP signals through the Serper API.",
    },
    {
        "module_key": "r.analysis",
        "service_id": "google_ads",
        "binding_status": "restricted",
        "allowed_capabilities": ["data_acquisition"],
        "reason": "R analysis pulls keyword volume from the Google Ads keyword planner.",
    },
    {
        "module_key": "r.analysis",
        "service_id": "deepseek",
        "binding_status": "restricted",
        "allowed_capabilities": ["reasoning"],
        "reason": "R analysis uses DeepSeek as the first-pass funnel filter after key binding.",
    },
    {
        "module_key": "r.analysis",
        "service_id": "chatgpt",
        "binding_status": "restricted",
        "allowed_capabilities": ["reasoning"],
        "reason": "R analysis uses GPT vision/terminal review in the selection funnel.",
    },
    {
        "module_key": "r.analysis",
        "service_id": "claude_opus",
        "binding_status": "restricted",
        "allowed_capabilities": ["reasoning"],
        "reason": "R analysis uses Claude Opus for on-demand deep report review.",
    },
    {
        "module_key": "f.enrichment",
        "service_id": "serper",
        "binding_status": "restricted",
        "allowed_capabilities": ["data_acquisition"],
        "reason": "F enrichment harvests per-category keywords through the Serper API.",
    },
    {
        "module_key": "f.enrichment",
        "service_id": "alibaba1688",
        "binding_status": "restricted",
        "allowed_capabilities": ["data_acquisition"],
        "reason": "F enrichment sources category candidates from 1688 keyword search.",
    },
    {
        "module_key": "w.site_ops",
        "service_id": "track17",
        "binding_status": "restricted",
        "allowed_capabilities": ["data_acquisition"],
        "reason": "W-S logistics pulls shipment tracking through the 17TRACK API.",
    },
    {
        "module_key": "communication.im",
        "service_id": "chat_record_store",
        "binding_status": "restricted",
        "allowed_capabilities": ["record_storage"],
        "reason": "C19 persists conversation records only in the configured record store.",
    },
    {
        "module_key": "communication.im",
        "service_id": "chat_asset_store",
        "binding_status": "restricted",
        "allowed_capabilities": ["record_storage"],
        "reason": "C19 persists chat media assets only in the configured asset store.",
    },
)

MODULE_CAPABILITY_BINDINGS_V1: tuple[dict[str, Any], ...] = (
    {
        "module_key": "k.product_knowledge",
        "allowed_capabilities": ["serp", "reasoning", "writing"],
        "binding_status": "restricted",
        "reason": "K product knowledge is restricted to product research and enrichment capabilities.",
    },
    {
        "module_key": "integration.n8n_test_bridge",
        "allowed_capabilities": [],
        "binding_status": "disabled",
        "reason": (
            "The test bridge has no serp, reasoning, writing, or "
            "embedding grant."
        ),
    },
    {
        "module_key": "p.upload",
        "allowed_capabilities": ["writing", "commerce_publish"],
        "binding_status": "restricted",
        "reason": "P upload is restricted to n8n dispatch and WooCommerce publishing.",
    },
    {
        "module_key": "r.warehouse",
        "allowed_capabilities": ["data_acquisition", "reasoning"],
        "binding_status": "restricted",
        "reason": "R warehouse is restricted to Keepa ingestion and DeepSeek screening.",
    },
    {
        "module_key": "r.analysis",
        "allowed_capabilities": ["data_acquisition", "reasoning"],
        "binding_status": "restricted",
        "reason": "R analysis is restricted to market data acquisition and AI funnel reasoning.",
    },
    {
        "module_key": "f.enrichment",
        "allowed_capabilities": ["data_acquisition"],
        "binding_status": "restricted",
        "reason": "F enrichment is restricted to keyword and sourcing data acquisition.",
    },
    {
        "module_key": "w.site_ops",
        "allowed_capabilities": ["data_acquisition"],
        "binding_status": "restricted",
        "reason": "W-S logistics is restricted to shipment tracking data acquisition.",
    },
    {
        "module_key": "communication.im",
        "allowed_capabilities": ["record_storage"],
        "binding_status": "restricted",
        "reason": "C19 communication is restricted to configured record/asset storage.",
    },
)

SERVICE_CAPABILITY_MAPPINGS_V1: tuple[dict[str, Any], ...] = (
    {
        "service_id": "serp",
        "capabilities": ["serp"],
        "binding_status": "restricted",
        "reason": "SERP service is restricted to search result acquisition.",
    },
    {
        "service_id": "deepseek",
        "capabilities": ["reasoning", "writing"],
        "binding_status": "restricted",
        "reason": "DeepSeek service is restricted to product enrichment.",
    },
    {
        "service_id": "chatgpt",
        "capabilities": ["reasoning", "writing"],
        "binding_status": "restricted",
        "reason": "ChatGPT service is restricted to first-pass keyword filtering.",
    },
    {
        "service_id": "claude_opus",
        "capabilities": ["reasoning", "writing"],
        "binding_status": "restricted",
        "reason": "Claude Opus service is restricted to second-pass keyword filtering.",
    },
    {
        "service_id": "ai_provider",
        "capabilities": ["reasoning", "writing"],
        "binding_status": "restricted",
        "reason": "AI provider service is restricted to product reasoning tasks.",
    },
    {
        "service_id": "n8n",
        "capabilities": ["writing"],
        "binding_status": "restricted",
        "reason": "n8n service is restricted to declared downstream handoff tasks.",
    },
    {
        "service_id": "woocommerce",
        "capabilities": ["commerce_publish"],
        "binding_status": "restricted",
        "reason": "WooCommerce is restricted to listing create/update via the n8n workflow.",
    },
    {
        "service_id": "keepa",
        "capabilities": ["data_acquisition"],
        "binding_status": "restricted",
        "reason": "Keepa is restricted to Amazon product data acquisition.",
    },
    {
        "service_id": "alibaba1688",
        "capabilities": ["data_acquisition"],
        "binding_status": "restricted",
        "reason": "1688 open platform is restricted to supplier keyword/image search.",
    },
    {
        "service_id": "rainforest",
        "capabilities": ["data_acquisition"],
        "binding_status": "restricted",
        "reason": "Rainforest is restricted to Amazon competition data acquisition.",
    },
    {
        "service_id": "serper",
        "capabilities": ["data_acquisition"],
        "binding_status": "restricted",
        "reason": "Serper is restricted to channel SERP signal acquisition.",
    },
    {
        "service_id": "google_ads",
        "capabilities": ["data_acquisition"],
        "binding_status": "restricted",
        "reason": "Google Ads keyword planner is restricted to keyword volume acquisition.",
    },
    {
        "service_id": "track17",
        "capabilities": ["data_acquisition"],
        "binding_status": "restricted",
        "reason": "17TRACK is restricted to shipment tracking data acquisition.",
    },
    {
        "service_id": "chat_record_store",
        "capabilities": ["record_storage"],
        "binding_status": "restricted",
        "reason": "The chat record store only persists C19 conversation records.",
    },
    {
        "service_id": "chat_asset_store",
        "capabilities": ["record_storage"],
        "binding_status": "restricted",
        "reason": "The chat asset store only persists C19 chat media assets.",
    },
)
