from typing import Any


def _navigation(
    *,
    group: str,
    label: str,
    icon: str,
    order: int,
    default_visible: bool = True,
    owner_only: bool = False,
) -> dict[str, object]:
    return {
        "group": group,
        "label": label,
        "icon": icon,
        "order": order,
        "default_visible": default_visible,
        "owner_only": owner_only,
    }


def _permission(
    *,
    module_key: str,
    permission_key: str,
    category: str,
    action: str,
    label: str,
    description: str,
    risk_level: str = "low",
    menu_policy: str = "show_locked",
    allowed_scope_types: tuple[str, ...] = ("global", "module"),
    high_risk_confirmation_required: bool = False,
    operation_log_required: bool = False,
) -> dict[str, object]:
    return {
        "permission_key": permission_key,
        "module_key": module_key,
        "category": category,
        "action": action,
        "label": label,
        "description": description,
        "risk_level": risk_level,
        "menu_policy": menu_policy,
        "default_scope_type": "global",
        "allowed_scope_types": list(allowed_scope_types),
        "high_risk_confirmation_required": high_risk_confirmation_required,
        "operation_log_required": operation_log_required,
    }


def _operation_log_policy(
    *,
    read: str = "optional",
    write: str = "required",
    approve: str = "required",
    release: str = "required",
) -> dict[str, str]:
    return {
        "read": read,
        "write": write,
        "approve": approve,
        "release": release,
    }


def _data_boundary(
    *,
    reads: tuple[str, ...] = (),
    writes: tuple[str, ...] = (),
    blocked_objects: tuple[str, ...] = (
        "server_local_config",
        "external_provider_config",
        "cross_module_writes",
    ),
) -> dict[str, list[str]]:
    return {
        "reads": list(reads),
        "writes": list(writes),
        "blocked_objects": list(blocked_objects),
    }


def _release_requirements(
    *,
    staging_acceptance: bool = False,
    production_archive: bool = False,
    required_checks: tuple[str, ...] = (),
) -> dict[str, object]:
    return {
        "local_verify": True,
        "staging_acceptance": staging_acceptance,
        "production_archive": production_archive,
        "required_checks": list(required_checks),
    }


def _manifest(
    *,
    module_key: str,
    display_name: str,
    description: str,
    category: str,
    status: str,
    lifecycle: str,
    route_namespace: str,
    api_namespace: str,
    navigation: dict[str, object],
    required_permissions: tuple[str, ...] = (),
    permission_manifest: tuple[dict[str, object], ...] = (),
    denied_behavior: str,
    unavailable_behavior: str = "show_unavailable",
    external_dependencies: tuple[str, ...] = (),
    execution_provider_required: bool = False,
    module_adapter_required: bool = False,
    sandbox_required: bool = False,
    feature_flag_key: str | None = None,
    audit_log_actions: tuple[str, ...] = (),
    operation_log_policy: dict[str, str] | None = None,
    allowed_scope_types: tuple[str, ...] = ("global", "module"),
    data_boundary: dict[str, list[str]] | None = None,
    release_requirements: dict[str, object] | None = None,
    staging_acceptance_required: bool = False,
    production_release_required: bool = False,
    docs_path: str = "docs/C07_MODULE_REGISTRY_BACKEND.md",
    no_api: bool = False,
) -> dict[str, Any]:
    return {
        "module_key": module_key,
        "display_name": display_name,
        "description": description,
        "category": category,
        "status": status,
        "lifecycle": lifecycle,
        "route_namespace": route_namespace,
        "api_namespace": api_namespace,
        "no_api": no_api,
        "navigation": navigation,
        "required_permissions": list(required_permissions),
        "permission_manifest": list(permission_manifest),
        "denied_behavior": denied_behavior,
        "unavailable_behavior": unavailable_behavior,
        "external_dependencies": list(external_dependencies),
        "execution_provider_required": execution_provider_required,
        "module_adapter_required": module_adapter_required,
        "sandbox_required": sandbox_required,
        "feature_flag_key": feature_flag_key,
        "audit_log_actions": list(audit_log_actions),
        "operation_log_policy": operation_log_policy or _operation_log_policy(),
        "allowed_scope_types": list(allowed_scope_types),
        "data_boundary": data_boundary or _data_boundary(),
        "release_requirements": release_requirements
        or _release_requirements(),
        "staging_acceptance_required": staging_acceptance_required,
        "production_release_required": production_release_required,
        "docs_path": docs_path,
    }


MODULE_MANIFESTS_V1: tuple[dict[str, Any], ...] = (
    _manifest(
        module_key="core.dashboard",
        display_name="Dashboard",
        description=(
            "Console overview shell for safe operational summaries and "
            "empty-state navigation."
        ),
        category="core",
        status="sealed",
        lifecycle="sealed",
        route_namespace="/dashboard",
        api_namespace="no_api",
        no_api=True,
        navigation=_navigation(
            group="Overview",
            label="Dashboard",
            icon="LayoutDashboard",
            order=10,
        ),
        denied_behavior="hide_when_denied",
        unavailable_behavior="hide",
        operation_log_policy=_operation_log_policy(write="none"),
    ),
    _manifest(
        module_key="communication.im",
        display_name="C19 Communication",
        description=(
            "Global communication, friendship, group chat, messaging, assets, "
            "and Moments available to every active authenticated user. "
            "Organization affiliations are optional descriptive context."
        ),
        category="core",
        status="active",
        lifecycle="production_released",
        route_namespace="/c19",
        api_namespace="/c19",
        no_api=False,
        navigation=_navigation(
            group="Communication",
            label="Communication",
            icon="MessageCircle",
            order=10,
            default_visible=True,
        ),
        required_permissions=(),
        permission_manifest=(),
        denied_behavior="show_locked",
        unavailable_behavior="show_unavailable",
        external_dependencies=("chat_record_store", "chat_asset_store"),
        module_adapter_required=True,
        feature_flag_key="modules.communication.im",
        audit_log_actions=(
            "communication.message.sent",
            "communication.friend.managed",
            "communication.group.created",
            "communication.group.managed",
            "communication.moment.published",
            "communication.attachment.uploaded",
            "communication.moderation.managed",
        ),
        allowed_scope_types=("global",),
        data_boundary=_data_boundary(
            reads=(
                "c19_profiles",
                "c19_affiliations",
                "c19_friend_requests",
                "c19_relationships",
                "c19_user_blocks",
                "c19_conversations",
                "c19_conversation_members",
                "c19_conversation_user_settings",
            ),
            writes=(
                "c19_profiles",
                "c19_affiliations",
                "c19_friend_requests",
                "c19_relationships",
                "c19_user_blocks",
                "c19_conversations",
                "c19_conversation_members",
                "c19_conversation_user_settings",
            ),
            blocked_objects=(
                "external_chat_content",
                "external_chat_assets",
                "external_chat_storage_configuration",
                "server_local_config",
                "external_provider_config",
                "cross_module_writes",
            ),
        ),
        release_requirements=_release_requirements(
            staging_acceptance=True,
            production_archive=True,
            required_checks=(
                "c19 record store configured",
                "c19 asset store configured",
                "c19 active-user native access",
                "c19 content isolation",
            ),
        ),
        staging_acceptance_required=True,
        production_release_required=True,
        docs_path="docs/C19_IMPLEMENTATION_MEMORY.md",
    ),
    _manifest(
        module_key="experimental.foundation_demo",
        display_name="Foundation Demo",
        description=(
            "Internal foundation exercise loop that writes demo-only records "
            "and never represents business completion."
        ),
        category="experimental",
        status="enabled",
        lifecycle="production_released",
        route_namespace="/foundation-demo",
        api_namespace="/foundation-demo",
        navigation=_navigation(
            group="Overview",
            label="Foundation Demo",
            icon="Activity",
            order=20,
        ),
        required_permissions=("modules.read",),
        permission_manifest=(
            _permission(
                module_key="experimental.foundation_demo",
                permission_key="modules.read",
                category="experimental",
                action="read",
                label="Read foundation demo metadata",
                description="View the internal demo-only foundation exercise metadata.",
                risk_level="low",
                menu_policy="hide_when_denied",
            ),
        ),
        denied_behavior="hide_when_denied",
        audit_log_actions=("foundation_demo.run",),
        data_boundary=_data_boundary(
            reads=("foundation_demo_metadata",),
            writes=("foundation_demo_metadata",),
        ),
    ),
    _manifest(
        module_key="integration.n8n_test_bridge",
        display_name="n8n Test Bridge",
        description=(
            "Test-only integration bridge metadata for the existing demo loop; "
            "C07B does not connect or configure real n8n."
        ),
        category="integration",
        status="adapter_pending",
        lifecycle="designed",
        route_namespace="/n8n-test",
        api_namespace="/n8n-test",
        navigation=_navigation(
            group="Overview",
            label="n8n Test Bridge",
            icon="Workflow",
            order=30,
            default_visible=False,
        ),
        required_permissions=("modules.read",),
        permission_manifest=(
            _permission(
                module_key="integration.n8n_test_bridge",
                permission_key="modules.read",
                category="integration",
                action="read",
                label="Read n8n test bridge metadata",
                description="View the existing test-only bridge metadata.",
                risk_level="low",
                menu_policy="hide_when_denied",
            ),
        ),
        denied_behavior="hide_when_denied",
        unavailable_behavior="adapter_pending",
        external_dependencies=("n8n",),
        module_adapter_required=True,
        sandbox_required=True,
        feature_flag_key="modules.integration.n8n_test_bridge",
        audit_log_actions=("n8n_test.run", "n8n_test.callback"),
        release_requirements=_release_requirements(
            required_checks=("mocked bridge tests",)
        ),
    ),
    _manifest(
        module_key="admin.users",
        display_name="User Management",
        description=(
            "Internal user management for owner and organization administrator "
            "sub-account lifecycle operations."
        ),
        category="admin",
        status="sealed",
        lifecycle="sealed",
        route_namespace="/users",
        api_namespace="/users",
        navigation=_navigation(
            group="System",
            label="User Management",
            icon="UserRoundCog",
            order=10,
        ),
        required_permissions=("users.manage",),
        permission_manifest=(
            _permission(
                module_key="admin.users",
                permission_key="users.read",
                category="admin",
                action="read",
                label="Read users",
                description="View internal user accounts and safe metadata.",
                risk_level="medium",
                menu_policy="hide_when_denied",
            ),
            _permission(
                module_key="admin.users",
                permission_key="users.manage",
                category="admin",
                action="manage",
                label="Manage users",
                description="Create and maintain internal non-owner accounts.",
                risk_level="high",
                menu_policy="hide_when_denied",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
        ),
        denied_behavior="hide_when_denied",
        audit_log_actions=(
            "user.create",
            "user.update",
            "user.disable",
            "user.enable",
        ),
        data_boundary=_data_boundary(reads=("users",), writes=("users",)),
        release_requirements=_release_requirements(
            production_archive=True,
            required_checks=("user API role-scope regression",),
        ),
        production_release_required=True,
    ),
    _manifest(
        module_key="admin.organizations",
        display_name="Organizations",
        description="Organization lifecycle management backed by existing organization APIs.",
        category="admin",
        status="enabled",
        lifecycle="production_released",
        route_namespace="/organizations",
        api_namespace="/organizations",
        navigation=_navigation(
            group="System",
            label="Organizations",
            icon="Building2",
            order=15,
        ),
        required_permissions=("users.manage",),
        permission_manifest=(
            _permission(
                module_key="admin.organizations",
                permission_key="users.manage",
                category="admin",
                action="manage",
                label="Manage organizations",
                description="Create and maintain organizations through existing user management controls.",
                risk_level="high",
                menu_policy="hide_when_denied",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
        ),
        denied_behavior="hide_when_denied",
        audit_log_actions=(
            "organization.create",
            "organization.update",
            "organization.delete",
            "organization.activate",
            "organization.suspend",
        ),
        data_boundary=_data_boundary(
            reads=("organizations", "users"),
            writes=("organizations",),
        ),
        release_requirements=_release_requirements(
            required_checks=("organization lifecycle API regression",),
        ),
    ),
    _manifest(
        module_key="admin.permissions",
        display_name="Permission Management",
        description=(
            "Permission assignment and registry management surface from C05 "
            "and C06 for owner and organization administrators."
        ),
        category="admin",
        status="sealed",
        lifecycle="sealed",
        route_namespace="/permissions",
        api_namespace="/permissions",
        navigation=_navigation(
            group="System",
            label="Permission Management",
            icon="LockKeyhole",
            order=20,
        ),
        required_permissions=("permissions.read",),
        permission_manifest=(
            _permission(
                module_key="admin.permissions",
                permission_key="permissions.read",
                category="admin",
                action="read",
                label="Read permissions",
                description="View permission registry and assignment state.",
                risk_level="medium",
                menu_policy="hide_when_denied",
            ),
            _permission(
                module_key="admin.permissions",
                permission_key="permissions.manage",
                category="admin",
                action="manage",
                label="Manage permissions",
                description="Grant, update, or revoke explicit assignments.",
                risk_level="critical",
                menu_policy="hide_when_denied",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
        ),
        denied_behavior="hide_when_denied",
        audit_log_actions=(
            "permission.assignment.grant",
            "permission.assignment.update",
            "permission.assignment.revoke",
        ),
        data_boundary=_data_boundary(
            reads=("permission_registry", "user_permission_assignments"),
            writes=("user_permission_assignments",),
        ),
        release_requirements=_release_requirements(
            production_archive=True,
            required_checks=("C06B assignment API regression",),
        ),
        production_release_required=True,
    ),
    _manifest(
        module_key="admin.modules",
        display_name="Module Control",
        description=(
            "Module control center plus C07B read-only manifest registry "
            "endpoints."
        ),
        category="admin",
        status="sealed",
        lifecycle="sealed",
        route_namespace="/module-control",
        api_namespace="/modules",
        navigation=_navigation(
            group="Registry",
            label="Module Control",
            icon="Boxes",
            order=20,
            owner_only=True,
        ),
        required_permissions=("modules.read",),
        permission_manifest=(
            _permission(
                module_key="admin.modules",
                permission_key="modules.read",
                category="admin",
                action="read",
                label="Read modules",
                description="View safe module registry metadata.",
                risk_level="low",
                menu_policy="hide_when_denied",
            ),
            _permission(
                module_key="admin.modules",
                permission_key="modules.manage",
                category="admin",
                action="manage",
                label="Manage modules",
                description="Reserved future module registry management.",
                risk_level="high",
                menu_policy="hide_when_denied",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
        ),
        denied_behavior="hide_when_denied",
        audit_log_actions=("module.create_demo",),
        data_boundary=_data_boundary(reads=("module_registry",)),
    ),
    _manifest(
        module_key="admin.key_management",
        display_name="API Key Management",
        description="API key management module entry for organization administrators.",
        category="admin",
        status="sealed",
        lifecycle="sealed",
        route_namespace="/api-key-management",
        api_namespace="/api-key-orchestration",
        navigation=_navigation(
            group="Registry",
            label="API Key Management",
            icon="LockKeyhole",
            order=25,
            owner_only=True,
        ),
        required_permissions=("modules.read",),
        permission_manifest=(
            _permission(
                module_key="admin.key_management",
                permission_key="modules.read",
                category="admin",
                action="read",
                label="Read API key management module",
                description="View API key management module metadata and entry point.",
                risk_level="medium",
                menu_policy="hide_when_denied",
            ),
        ),
        denied_behavior="hide_when_denied",
        data_boundary=_data_boundary(reads=("credential_registry",)),
    ),
    _manifest(
        module_key="admin.key_health",
        display_name="API Key Health",
        description="Owner-only hourly credential availability monitoring.",
        category="admin",
        status="sealed",
        lifecycle="sealed",
        route_namespace="/key-health",
        api_namespace="/key-health",
        navigation=_navigation(
            group="Registry",
            label="API Key Health",
            icon="ShieldCheck",
            order=26,
            owner_only=True,
        ),
        required_permissions=("modules.read",),
        permission_manifest=(
            _permission(
                module_key="admin.key_health",
                permission_key="modules.read",
                category="admin",
                action="read",
                label="Read API key health",
                description="View secret-free API key health results.",
                risk_level="medium",
                menu_policy="hide_when_denied",
            ),
        ),
        denied_behavior="hide_when_denied",
        audit_log_actions=("key_health.run",),
        data_boundary=_data_boundary(
            reads=("credential_registry", "key_health_results"),
            writes=("key_health_results", "owner_notifications"),
        ),
    ),
    _manifest(
        module_key="admin.agents",
        display_name="Agents",
        description="Existing foundation agent metadata registry page.",
        category="admin",
        status="sealed",
        lifecycle="sealed",
        route_namespace="/agents",
        api_namespace="/agents",
        navigation=_navigation(
            group="Registry",
            label="Agents",
            icon="Bot",
            order=30,
        ),
        required_permissions=("modules.read",),
        permission_manifest=(
            _permission(
                module_key="admin.agents",
                permission_key="modules.read",
                category="admin",
                action="read",
                label="Read agent registry",
                description="View safe agent registry metadata.",
                risk_level="low",
                menu_policy="hide_when_denied",
            ),
        ),
        denied_behavior="hide_when_denied",
        data_boundary=_data_boundary(reads=("agent_registry",)),
    ),
    _manifest(
        module_key="admin.settings",
        display_name="Settings",
        description=(
            "Planned safe settings shell; C07B exposes metadata only and no "
            "settings write path."
        ),
        category="admin",
        status="planned",
        lifecycle="designed",
        route_namespace="/settings",
        api_namespace="no_api",
        no_api=True,
        navigation=_navigation(
            group="System",
            label="Settings",
            icon="Settings",
            order=30,
            default_visible=False,
        ),
        required_permissions=("settings.read",),
        permission_manifest=(
            _permission(
                module_key="admin.settings",
                permission_key="settings.read",
                category="admin",
                action="read",
                label="Read settings",
                description="View safe settings metadata when implemented.",
                risk_level="medium",
                menu_policy="hide_when_denied",
            ),
            _permission(
                module_key="admin.settings",
                permission_key="settings.manage",
                category="admin",
                action="manage",
                label="Manage settings",
                description="Reserved future settings management.",
                risk_level="critical",
                menu_policy="hide_when_denied",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
        ),
        denied_behavior="hide_when_denied",
        unavailable_behavior="planned",
        feature_flag_key="modules.admin.settings",
    ),
    _manifest(
        module_key="k.product_knowledge",
        display_name="Product Knowledge",
        description=(
            "K-series product knowledge workspace with persistent product, "
            "keyword, risk, media, and provider-gated enrichment APIs."
        ),
        category="business",
        status="active",
        lifecycle="production_released",
        route_namespace="/products",
        api_namespace="/k",
        navigation=_navigation(
            group="Registry",
            label="产品知识库",
            icon="PackageSearch",
            order=8,
        ),
        required_permissions=("products.read",),
        permission_manifest=(
            _permission(
                module_key="k.product_knowledge",
                permission_key="products.read",
                category="business",
                action="read",
                label="Read products",
                description="View product knowledge records through the products workspace.",
                risk_level="low",
                menu_policy="show_locked",
            ),
            _permission(
                module_key="k.product_knowledge",
                permission_key="k.product_knowledge.read",
                category="business",
                action="read",
                label="Read product knowledge",
                description="View K-series product knowledge records.",
                risk_level="low",
                menu_policy="show_locked",
            ),
            _permission(
                module_key="k.product_knowledge",
                permission_key="k.product_knowledge.create",
                category="business",
                action="create",
                label="Create product knowledge",
                description="Create K-series product knowledge records.",
                risk_level="medium",
                menu_policy="show_locked",
                operation_log_required=True,
            ),
            _permission(
                module_key="k.product_knowledge",
                permission_key="k.product_knowledge.update",
                category="business",
                action="update",
                label="Update product knowledge",
                description="Edit K-series product knowledge records.",
                risk_level="medium",
                menu_policy="show_locked",
                operation_log_required=True,
            ),
            _permission(
                module_key="k.product_knowledge",
                permission_key="k.product_knowledge.archive",
                category="business",
                action="archive",
                label="Archive product knowledge",
                description="Archive K-series product knowledge records.",
                risk_level="high",
                menu_policy="show_locked",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
            _permission(
                module_key="k.product_knowledge",
                permission_key="k.product_knowledge.attributes.manage",
                category="business",
                action="manage",
                label="Manage product attributes",
                description="Create or update K-series product attributes.",
                risk_level="medium",
                menu_policy="show_locked",
                operation_log_required=True,
            ),
            _permission(
                module_key="k.product_knowledge",
                permission_key="k.product_knowledge.keywords.manage",
                category="business",
                action="manage",
                label="Manage product keywords",
                description="Create, update, approve, or archive K-series keywords.",
                risk_level="medium",
                menu_policy="show_locked",
                operation_log_required=True,
            ),
            _permission(
                module_key="k.product_knowledge",
                permission_key="k.product_knowledge.risk_terms.manage",
                category="business",
                action="manage",
                label="Manage product risk terms",
                description="Create, update, resolve, or ignore K-series risk terms.",
                risk_level="high",
                menu_policy="show_locked",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
            _permission(
                module_key="k.product_knowledge",
                permission_key="k.product_knowledge.workflow.execute",
                category="business",
                action="execute",
                label="Execute product knowledge workflow",
                description=(
                    "Run the gated K-series product knowledge pipeline up to "
                    "manual review checkpoints."
                ),
                risk_level="high",
                menu_policy="show_locked",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
            _permission(
                module_key="k.product_knowledge",
                permission_key="k.product_knowledge.export",
                category="business",
                action="export",
                label="Export product knowledge payloads",
                description=(
                    "Export P-series, GMC, and SEO payloads only after the "
                    "full K workflow gate is satisfied."
                ),
                risk_level="critical",
                menu_policy="show_locked",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
        ),
        denied_behavior="show_locked",
        unavailable_behavior="show_unavailable",
        external_dependencies=(
            "serp",
            "chatgpt",
            "claude_opus",
            "deepseek",
            "ai_provider",
            "n8n",
        ),
        execution_provider_required=True,
        module_adapter_required=True,
        sandbox_required=True,
        audit_log_actions=(
            "k.product_knowledge.created",
            "k.product_knowledge.updated",
            "k.product_knowledge.archived",
            "k.product_knowledge.keyword.updated",
            "k.product_knowledge.risk_term.updated",
            "k.product_knowledge.enrichment.executed",
            "k.product_knowledge.workflow.executed",
            "k.product_knowledge.export.generated",
        ),
        data_boundary=_data_boundary(
            reads=(
                "k_product_knowledge_products",
                "k_product_knowledge_keywords",
                "k_product_knowledge_risk_terms",
                "k_product_knowledge_workflow_executions",
                "credential_module_bindings",
            ),
            writes=(
                "k_product_knowledge_products",
                "k_product_knowledge_keywords",
                "k_product_knowledge_risk_terms",
                "k_product_knowledge_media_assets",
                "k_product_knowledge_ai_events",
                "k_product_knowledge_workflow_executions",
            ),
        ),
        release_requirements=_release_requirements(
            staging_acceptance=True,
            production_archive=True,
            required_checks=(
                "k product persistence",
                "k api key binding",
                "k execution gate",
                "k dual ai filter",
                "k manual risk review",
                "k guarded export",
            ),
        ),
        staging_acceptance_required=True,
        production_release_required=True,
    ),
    _manifest(
        module_key="i.image_system",
        display_name="I Image System",
        description=(
            "Independent I-series AI image system boundary for image generation, "
            "image editing, isolated media library storage, and API-level "
            "product/variant handoff to K-series."
        ),
        category="business",
        status="active",
        lifecycle="production_released",
        route_namespace="/image-system",
        api_namespace="/i",
        navigation=_navigation(
            group="Registry",
            label="I系列图片系统",
            icon="Images",
            order=9,
        ),
        required_permissions=("i.image_system.read",),
        permission_manifest=(
            _permission(
                module_key="i.image_system",
                permission_key="i.image_system.read",
                category="business",
                action="read",
                label="Read I image system metadata",
                description="View the independent I-series image system boundary metadata.",
                risk_level="low",
                menu_policy="show_locked",
            ),
            _permission(
                module_key="i.image_system",
                permission_key="i.image_system.execute",
                category="business",
                action="execute",
                label="Generate and edit I-series images",
                description="Run prompt enhancement, image generation, and image editing.",
                risk_level="medium",
                menu_policy="show_locked",
                operation_log_required=True,
            ),
            _permission(
                module_key="i.image_system",
                permission_key="i.image_system.manage",
                category="business",
                action="manage",
                label="Manage I-series media library",
                description="Save, download, and delete I-series media library images.",
                risk_level="medium",
                menu_policy="show_locked",
                operation_log_required=True,
            ),
        ),
        denied_behavior="show_locked",
        unavailable_behavior="show_unavailable",
        # I 的执行门禁是动作级的（/images/generate 调用时 resolve key），
        # 不需要预注册 execution provider —— True 会让侧边栏误判 no_execution 变暗。
        execution_provider_required=False,
        module_adapter_required=False,
        sandbox_required=False,
        feature_flag_key="modules.i.image_system",
        data_boundary=_data_boundary(
            reads=("i_image_assets",),
            writes=("i_image_assets",),
        ),
        release_requirements=_release_requirements(
            staging_acceptance=True,
            production_archive=True,
            required_checks=("future I-series adapter acceptance",),
        ),
        staging_acceptance_required=True,
        production_release_required=True,
    ),
    _manifest(
        module_key="p.upload",
        display_name="P系列自动化上传",
        description=(
            "P-series automated publishing control plane: gate-checked upload "
            "packages (copy + rendered images + media SEO), dispatch to n8n, "
            "WooCommerce create/update via SKU upsert, and the upload ledger."
        ),
        category="business",
        status="active",
        lifecycle="production_released",
        route_namespace="/p-upload",
        api_namespace="/p",
        navigation=_navigation(
            group="Registry",
            label="P系列自动化上传",
            icon="UploadCloud",
            order=10,
        ),
        denied_behavior="show_locked",
        unavailable_behavior="show_unavailable",
        external_dependencies=("n8n", "woocommerce"),
        execution_provider_required=False,
        module_adapter_required=False,
        sandbox_required=False,
        feature_flag_key="modules.p.upload",
        data_boundary=_data_boundary(
            reads=("p_upload_jobs", "k_product_knowledge_products"),
            writes=("p_upload_jobs",),
        ),
        release_requirements=_release_requirements(
            staging_acceptance=True,
            production_archive=True,
            required_checks=("n8n upload workflow contract",),
        ),
        staging_acceptance_required=True,
        production_release_required=True,
    ),
    _manifest(
        module_key="r.warehouse",
        display_name="R-W 产品数据仓库",
        description=(
            "R-series Warehouse realtime Keepa ingestion, category scheduling, "
            "normalized product storage, rule filtering, and DeepSeek first-pass "
            "screening."
        ),
        category="business",
        status="active",
        lifecycle="production_released",
        route_namespace="/r-w",
        api_namespace="/rw",
        navigation=_navigation(
            group="Registry",
            label="R-W 产品数据仓库",
            icon="Database",
            order=11,
        ),
        denied_behavior="show_locked",
        unavailable_behavior="show_unavailable",
        external_dependencies=("keepa", "deepseek"),
        execution_provider_required=False,
        module_adapter_required=False,
        sandbox_required=False,
        feature_flag_key="modules.r.warehouse",
        audit_log_actions=(
            "r.warehouse.products.read",
            "r.warehouse.status.read",
            "r.warehouse.rules.read",
        ),
        data_boundary=_data_boundary(
            reads=("products_rw", "enrich_queue", "rule_results", "ai_evaluations"),
            writes=("products_rw", "enrich_queue", "rule_results", "ai_evaluations"),
            blocked_objects=("r_analysis_runtime", "cross_module_writes"),
        ),
        release_requirements=_release_requirements(
            staging_acceptance=True,
            production_archive=True,
            required_checks=(
                "rw realtime worker heartbeat",
                "rw frontend live backend audit",
                "keepa category scheduler active",
            ),
        ),
        staging_acceptance_required=True,
        production_release_required=True,
        docs_path="r_system_v2/docs/ARCHITECTURE.md",
    ),
    _manifest(
        module_key="r.analysis",
        display_name="R-A 产品分析中心",
        description=(
            "R-series Analysis framework for candidate review, supplier cost, "
            "profit snapshots, Rainforest competition enrichment, real multi-AI review, and final product-selection "
            "reports. Real provider calls are enabled through module key bindings."
        ),
        category="business",
        status="active",
        lifecycle="production_released",
        route_namespace="/r-a",
        api_namespace="/r/analysis",
        no_api=False,
        navigation=_navigation(
            group="Registry",
            label="R-A 产品分析中心",
            icon="ClipboardCheck",
            order=12,
        ),
        denied_behavior="show_locked",
        unavailable_behavior="show_unavailable",
        external_dependencies=(
            "deepseek",
            "chatgpt",
            "claude_opus",
            "serper",
            "alibaba1688",
            "rainforest",
            "google_ads",
        ),
        execution_provider_required=False,
        module_adapter_required=False,
        sandbox_required=False,
        feature_flag_key="modules.r.analysis",
        data_boundary=_data_boundary(
            reads=("products_rw",),
            writes=(
                "ra_selection_runs",
                "ra_candidates",
                "ra_ai_evaluations",
                "ra_supplier_searches",
                "ra_supplier_offers",
                "ra_profit_snapshots",
                "ra_competition_snapshots",
                "ra_channel_signals",
                "ra_final_decisions",
                "ra_reports",
                "ra_alerts",
            ),
            blocked_objects=(
                "cross_module_writes",
            ),
        ),
        release_requirements=_release_requirements(
            required_checks=(
                "r-a framework api present",
                "r-a database boundary present",
                "r-a real ai e2e pipeline pass",
                "r-a provider key binding audit pass",
            ),
        ),
        docs_path="r_system_v2/docs/RA_TASKS.md",
    ),
    _manifest(
        module_key="f.enrichment",
        display_name="F 类目富化",
        description=(
            "F-series category enrichment: pick Google taxonomy branches "
            "(shared with K), harvest per-category keywords via Serper, build "
            "a 1688-sourced candidate pool with red-line flagging, and hand "
            "manually approved products to the K→I→P chain. 铺类目不选爆款。"
        ),
        category="business",
        status="active",
        lifecycle="production_released",
        route_namespace="/f-enrichment",
        api_namespace="/f",
        navigation=_navigation(
            group="Registry",
            label="F 类目富化",
            icon="GitBranch",
            order=14,
        ),
        required_permissions=("f.enrichment.read",),
        permission_manifest=(
            _permission(
                module_key="f.enrichment",
                permission_key="f.enrichment.read",
                category="business",
                action="read",
                label="Read category enrichment",
                description="View F-series enrichment runs, keywords, and candidates.",
                risk_level="low",
                menu_policy="show_locked",
            ),
            _permission(
                module_key="f.enrichment",
                permission_key="f.enrichment.execute",
                category="business",
                action="execute",
                label="Execute enrichment runs",
                description=(
                    "Start Serper keyword harvest runs over selected Google "
                    "taxonomy branches (consumes daily provider quota)."
                ),
                risk_level="medium",
                menu_policy="show_locked",
                operation_log_required=True,
            ),
            _permission(
                module_key="f.enrichment",
                permission_key="f.enrichment.review",
                category="business",
                action="manage",
                label="Review enrichment candidates",
                description=(
                    "Create and review sourcing candidates (approve / reject) "
                    "and import approved candidates into K."
                ),
                risk_level="medium",
                menu_policy="show_locked",
                operation_log_required=True,
            ),
        ),
        denied_behavior="show_locked",
        unavailable_behavior="show_unavailable",
        external_dependencies=("serper", "alibaba1688"),
        execution_provider_required=False,
        module_adapter_required=False,
        sandbox_required=False,
        feature_flag_key="modules.f.enrichment",
        audit_log_actions=(
            "f.enrichment.run.started",
            "f.enrichment.candidate.created",
            "f.enrichment.candidate.reviewed",
            "f.enrichment.imported_to_k",
        ),
        data_boundary=_data_boundary(
            reads=(
                "k_category_google",
                "f_enrichment_runs",
                "f_category_keywords",
                "f_category_candidates",
            ),
            writes=(
                "f_enrichment_runs",
                "f_category_keywords",
                "f_category_candidates",
                "k_product_knowledge_products",
            ),
            blocked_objects=("cross_module_writes",),
        ),
        release_requirements=_release_requirements(
            required_checks=(
                "f enrichment api present",
                "f quota ledger shared with r-a",
            ),
        ),
    ),
    _manifest(
        module_key="w.site_ops",
        display_name="W-S 物流网络中枢",
        description=(
            "W-S is a logistics hub for shipping template sync to WooCommerce, "
            "order tracking, and deterministic shipping-class assignment."
        ),
        category="business",
        status="active",
        lifecycle="production_released",
        route_namespace="/w-s",
        api_namespace="/w",
        navigation=_navigation(
            group="Registry",
            label="W-S 物流网络中枢",
            icon="Boxes",
            order=15,
        ),
        required_permissions=("w.site_ops.read",),
        permission_manifest=(
            _permission(
                module_key="w.site_ops",
                permission_key="w.site_ops.read",
                category="business",
                action="read",
                label="Read site operations",
                description="View shipping classes, rules, and product assignments.",
                risk_level="low",
                menu_policy="show_locked",
            ),
            _permission(
                module_key="w.site_ops",
                permission_key="w.site_ops.manage",
                category="business",
                action="manage",
                label="Manage site operations",
                description="Manage shipping classes, rules, and product assignments.",
                risk_level="medium",
                menu_policy="show_locked",
                operation_log_required=True,
            ),
        ),
        denied_behavior="show_locked",
        unavailable_behavior="show_unavailable",
        external_dependencies=("track17",),
        execution_provider_required=False,
        module_adapter_required=False,
        sandbox_required=False,
        feature_flag_key="modules.w.site_ops",
        data_boundary=_data_boundary(
            reads=(
                "w_shipping_classes",
                "w_shipping_rules",
                "w_sync_jobs",
                "w_orders",
                "k_product_knowledge_products",
            ),
            writes=(
                "w_shipping_classes",
                "w_shipping_rules",
                "w_sync_jobs",
                "w_orders",
                "k_product_knowledge_products",
            ),
            blocked_objects=("cross_module_writes",),
        ),
    ),
    _manifest(
        module_key="business.approvals",
        display_name="Approvals",
        description="Approval request list and decision surface.",
        category="business",
        status="enabled",
        lifecycle="production_released",
        route_namespace="/approvals",
        api_namespace="/approval",
        navigation=_navigation(
            group="Governance",
            label="Approvals",
            icon="ClipboardCheck",
            order=5,
        ),
        required_permissions=("reviews.read",),
        permission_manifest=(
            _permission(
                module_key="business.approvals",
                permission_key="reviews.read",
                category="business",
                action="read",
                label="Read approvals",
                description="View approval requests available to the current account.",
                risk_level="low",
                menu_policy="show_locked",
            ),
            _permission(
                module_key="business.approvals",
                permission_key="reviews.approve",
                category="business",
                action="approve",
                label="Approve requests",
                description="Approve or reject governed approval requests.",
                risk_level="high",
                menu_policy="show_locked",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
        ),
        denied_behavior="show_locked",
        audit_log_actions=(
            "approval.requested",
            "approval.approved",
            "approval.rejected",
        ),
        data_boundary=_data_boundary(
            reads=("approval_requests", "approval_decisions"),
            writes=("approval_requests", "approval_decisions"),
        ),
    ),
    _manifest(
        module_key="business.reviews",
        display_name="Approval Audit",
        description="Approval decision audit by organization, employee, and module.",
        category="business",
        status="enabled",
        lifecycle="production_released",
        route_namespace="/reviews",
        api_namespace="/reviews",
        navigation=_navigation(
            group="Governance",
            label="Reviews",
            icon="ClipboardCheck",
            order=10,
        ),
        required_permissions=("reviews.read",),
        permission_manifest=(
            _permission(
                module_key="business.reviews",
                permission_key="reviews.read",
                category="business",
                action="read",
                label="Read approval audit",
                description="View approval decision audit records.",
                risk_level="low",
                menu_policy="show_locked",
            ),
            _permission(
                module_key="business.reviews",
                permission_key="reviews.approve",
                category="business",
                action="approve",
                label="Approve reviews",
                description="Reserved review approval permission for governed workflows.",
                risk_level="high",
                menu_policy="show_locked",
                high_risk_confirmation_required=True,
                operation_log_required=True,
            ),
        ),
        denied_behavior="show_locked",
        audit_log_actions=("approval.approved", "approval.rejected"),
        data_boundary=_data_boundary(
            reads=("approval_decisions", "approval_requests"),
        ),
    ),
    _manifest(
        module_key="system.errors",
        display_name="Errors",
        description="System error metadata page for safe operational review.",
        category="system",
        status="enabled",
        lifecycle="production_released",
        route_namespace="/errors",
        api_namespace="/errors",
        navigation=_navigation(
            group="Governance",
            label="Errors",
            icon="CircleAlert",
            order=20,
        ),
        required_permissions=("operation_logs.read",),
        permission_manifest=(
            _permission(
                module_key="system.errors",
                permission_key="operation_logs.read",
                category="system",
                action="read",
                label="Read system errors",
                description="View safe error and operation metadata.",
                risk_level="high",
                menu_policy="hide_when_denied",
            ),
        ),
        denied_behavior="hide_when_denied",
        data_boundary=_data_boundary(reads=("system_errors",)),
    ),
    _manifest(
        module_key="system.memory_events",
        display_name="Memory Events",
        description="System memory event metadata page.",
        category="system",
        status="enabled",
        lifecycle="production_released",
        route_namespace="/memory-events",
        api_namespace="/memory-events",
        navigation=_navigation(
            group="Governance",
            label="Memory Events",
            icon="Database",
            order=30,
        ),
        required_permissions=("operation_logs.read",),
        permission_manifest=(
            _permission(
                module_key="system.memory_events",
                permission_key="operation_logs.read",
                category="system",
                action="read",
                label="Read memory events",
                description="View safe memory event metadata.",
                risk_level="high",
                menu_policy="hide_when_denied",
            ),
        ),
        denied_behavior="hide_when_denied",
        data_boundary=_data_boundary(reads=("memory_events",)),
    ),
    _manifest(
        module_key="system.operation_logs",
        display_name="Operation Logs",
        description="System audit log read surface.",
        category="system",
        status="sealed",
        lifecycle="sealed",
        route_namespace="/operation-logs",
        api_namespace="/operation-logs",
        navigation=_navigation(
            group="Governance",
            label="Operation Logs",
            icon="Database",
            order=40,
            default_visible=False,
        ),
        required_permissions=("operation_logs.read",),
        permission_manifest=(
            _permission(
                module_key="system.operation_logs",
                permission_key="operation_logs.read",
                category="system",
                action="read",
                label="Read operation logs",
                description="View audit log and operation history metadata.",
                risk_level="high",
                menu_policy="hide_when_denied",
            ),
        ),
        denied_behavior="hide_when_denied",
        data_boundary=_data_boundary(reads=("operation_logs",)),
    ),
)
